### ISSUE TITLE
Cannot start the service

### ISSUE THREAD

**Issue by arnaudom** [valory-xyz/trader-quickstart#204]
I have this issue when launching run_service, then launching exits
(windows 10):

------------------------------
Starting the trader service...
------------------------------
[docker]Step 1/11 : ARG AUTONOMY_IMAGE_VERSION="latest"[docker]
...
...
[docker]sha256:55be689e3397938965cdcffc11b82a6771b88f589c5f7d1ee554d358b73dfc13[docker]Successfully built 55be689e3397
[docker]Successfully tagged default_author/oar-trader:bafybeih6gz36goxhz4pxvcm7mcortunojmezcokdbxq5pqynbr7ndikrru
Building deployment @ F:\ApacheWeb\htdocs\trader-quickstart\trader\trader_service\abci_build
Traceback (most recent call last):
  File "C:\Users\x\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\x\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\x\AppData\Local\pypoetry\Cache\virtualenvs\trader-vJwdYzYc-py3.10\Scripts\autonomy.exe\__main__.py", line 7, in <module>
    sys.exit(cli())
  File "C:\Users\x\AppData\Local\pypoetry\Cache\virtualenvs\trader-vJwdYzYc-py3.10\lib\site-packages\click\core.py", line 1126, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\x\AppData\Local\pypoetry\Cache\virtualenvs\trader-vJwdYzYc-py3.10\lib\site-packages\click\core.py", line 1051, in main
    rv = self.invoke(ctx)
  File "C:\Users\x\AppData\Local\pypoetry\Cache\virtualenvs\trader-vJwdYzYc-py3.10\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\x\AppData\Local\pypoetry\Cache\virtualenvs\trader-vJwdYzYc-py3.10\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\x\AppData\Local\pypoetry\Cache\virtualenvs\trader-vJwdYzYc-py3.10\lib\site-packages\click\core.py", line 1393, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\x\AppData\Local\pypoetry\Cache\virtualenvs\trader-vJwdYzYc-py3.10\lib\site-packages\click\core.py", line 752, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\x\AppData\Local\pypoetry\Cache\virtualenvs\trader-vJwdYzYc-py3.10\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Users\x\AppData\Local\pypoetry\Cache\virtualenvs\trader-vJwdYzYc-py3.10\lib\site-packages\autonomy\cli\deploy.py", line 224, in build_deployment_command
    build_deployment(
  File "C:\Users\x\AppData\Local\pypoetry\Cache\virtualenvs\trader-vJwdYzYc-py3.10\lib\site-packages\autonomy\cli\helpers\deployment.py", line 211, in build_deployment
    report = generate_deployment(
  File "C:\Users\x\AppData\Local\pypoetry\Cache\virtualenvs\trader-vJwdYzYc-py3.10\lib\site-packages\autonomy\deploy\build.py", line 87, in generate_deployment
    deployment.generate(
  File "C:\Users\x\AppData\Local\pypoetry\Cache\virtualenvs\trader-vJwdYzYc-py3.10\lib\site-packages\autonomy\deploy\generators\docker_compose\base.py", line 248, in generate
    network = Network(name=network_name)
  File "C:\Users\x\AppData\Local\pypoetry\Cache\virtualenvs\trader-vJwdYzYc-py3.10\lib\site-packages\autonomy\deploy\generators\docker_compose\base.py", line 165, in __init__
    self.subnet = self.build()
  File "C:\Users\x\AppData\Local\pypoetry\Cache\virtualenvs\trader-vJwdYzYc-py3.10\lib\site-packages\autonomy\deploy\generators\docker_compose\base.py", line 191, in build
    for config in network.attrs["IPAM"]["Config"]:
TypeError: 'NoneType' object is not iterable
WARNING: `dependencies` parameter not defined in the service

**Comment by dagacha** [comment]
This is likely related to this requirement: [Docker Engine](https://docs.docker.com/engine/install/) <25.0.0

If this is the case then downgrading to a previous version of Docker should solve the problem.

**Comment by arnaudom** [comment]
Thank you! I downgraded the version and it went through.

Now, am facing errors with "sudo" command, i.e.:

> Generated Deployment!
> Type:                 docker-compose
> Agents:               1
> Build Length          12553
> ./run_service.sh: line 181: sudo: command not found

**Comment by dagacha** [comment]
What platform are you using?

**Comment by arnaudom** [comment]
Windows 10
WSL version: 2.0.9.0, Default Distribution: docker-desktop, Default Version: 2
git version 2.39.2.windows.1
Docker Desktop 4.26.1

Looks like I have a problem with WSL settings.

**Comment by dagacha** [comment]
FWIW The script was tested last week on a fresh [WSL2 Ubuntu 22.04](https://apps.microsoft.com/detail/9PN20MSR04DW?hl=en-US&gl=US) installation

https://learn.microsoft.com/en-us/windows/wsl/install-manual

**Comment by arnaudom** [comment]
The setup looks ok:

> λ wslconfig /l
> Windows Subsystem for Linux Distributions:
> Ubuntu-22.04 (Default)
> docker-desktop
> docker-desktop-data

But still facing same error.
I tried  different way to call the script, no difference.

Should the script run from windows Git Bash or Ubuntu terminal?

![wsl](https://github.com/valory-xyz/trader-quickstart/assets/1535627/31537b8a-c08f-4458-aa52-b4167247aebb)

**Comment by dagacha** [comment]
I've just pulled from main and run the script succesfully on my WSL2 Ubuntu-22.04 terminal, and the trader agent is placing bets and redeeming wins.

Have you checked if you can run `sudo` in the terminal (outside the script)? If not then I guess there is an issue with your local settings.

You can always try with Git Bash. In all honesty WSL2 has normaly worked better with this script.

**Comment by dagacha** [comment]
> run_service.sh: command not found

Have you run

`chmod +x run_service.sh`

beforehand?

**Comment by arnaudom** [comment]
Yes, the file is executable
![wsl](https://github.com/valory-xyz/trader-quickstart/assets/1535627/0ad909be-4bde-4302-a4f5-178887bb2709)

I tried all possible settings and conf, including wsl update.
Everything looks as per requirement, but still getting same error.
If I launch from Git bash, sudo not found, if I launch from wsl, run_service.sh: command not found.

**Comment by arnaudom** [comment]
Finally removed and reinstalled all required windows softwares, ubuntu distribution and managed to start the service !
Thank you.
![aiagent2](https://github.com/valory-xyz/trader-quickstart/assets/1535627/22ca010c-4f7f-4b8c-8d4a-c7f215787ce7)

**Comment by dagacha** [comment]
Excellent, well done! Your perserverance has paid off :-)
